### ISSUE TITLE
modules located in subfolders setup

### ISSUE THREAD

**Issue by engineer-go** [waliding/multimodule-ci-pipeline#1]
Can I ask what would be set up for the modules that are located inside other folders like this: 
```

/base/common
/base/heater
/base/propagator 
```

Especially for the module ci/cd file: 

Should it be

```yaml
.baseheater-module:
  variables:
    MODULE: base/heater
  only:
    changes:
        - "base/heater/**/*"
```

Or still be like: 
```yaml
.baseheater-module:
  variables:
    MODULE: heater
  only:
    changes:
        - "heater/**/*"
```
Since it is a module? 

I ask because, in my project, runners don't seem to pick up any changes either way( Trying to find a reason for such behavior.
